KDW-2458: Production k8s and readme update
KargoGlobal/lookerbot pull request #1
Opened 2019-07-02 14:56 UTC by caberson

https://kargo1.atlassian.net/browse/KDW-2657

Production bot is deployed.  Have switched Slack app and the one Looker report to point to the production instance. I will turn off the dev version after a day.

2019-07-02 15:10 UTC, chaithra-yenikapati approved these changes
👍

2019-07-02 15:23 UTC, transistorize commented on k8s/dev/deployment.yaml
> +              path: /health_check
nice! I need a tutorial on liveness and readiness probles

2019-07-08 16:42 UTC, transistorize requested changes

2019-07-08 16:42 UTC, transistorize commented on k8s/README.md
> +If existing secrets need update, you can use `template/secrets-template.yaml` as a template.  Update all the `FIXME` values.  Then apply the updated file to the applicable environment.
If existing secrets need `an` update

2019-07-08 16:42 UTC, transistorize commented on k8s/README.md
> +Ways to quickly check if the production Looker bot is active.  Note that unless you've confirmed the Looker bot you deployed was made active, the following methods may just mean the last active Looke
First sentence is a bit awkward, perhaps better as a subheading?

2019-07-08 17:07 UTC, caberson commented
@transistorize, made the changes to README.

2019-07-08 17:22 UTC, transistorize approved these changes

2019-07-08 17:22 UTC, merged